# Generated by Django 4.1.7 on 2023-02-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Image',
            new_name='image',
        ),
    ]
